{{- if .Values.api.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis-soc.fullname" . }}-secrets
  labels:
    {{- include "aegis-soc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.api.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
